### ISSUE TITLE
torch.cuda.is_available()为false

### ISSUE THREAD

**Issue by wujm7** [Houruizhi/IDPCNN#3]
作者您好，想请问一下您所用的各个包以及python的版本是多少哇 为什么我下载您的代码用不了cuda 但是其他所有程序都没问题 唯独您的这个代码显示torch.cuda.is_available()为false，请问是您所用的python版本太高了吗？

**Comment by Houruizhi** [comment]
把下面这两句删掉试试看呢？这个代码结构挺简单，用任何版本的pytorch应该都是可以的
```python
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ','.join([str(i) for i in cfg.SYSTEM.GPU_IDS[:cfg.SYSTEM.NUM_GPUS]])
```

**Comment by wujm7** [comment]
谢谢作者！上面那个问题解决了！但是又出现一个新问题说NotADirectoryError: [WinError 267] 目录名称无效。: './checkpoints/SIAT/SIAT_dncnn_15.0/net.pth'  请问这个是怎么回事啊？

**Comment by Houruizhi** [comment]
这就是你自己的路径问题了
